Added speedtest
Steellow/trapBot pull request #4
Opened 2022-01-12 12:30 UTC by Iikkas

2022-01-12 14:25 UTC, Steellow requested changes
1 lil change

2022-01-12 14:25 UTC, Steellow commented on speedtest.js
> +const nextDate = new Date();
Unused variable, should remove

2022-01-15 09:32 UTC, Iikkas commented on speedtest.js
> +const nextDate = new Date();
done

2022-01-15 10:58 UTC, Steellow approved these changes
lg2m

2022-01-15 10:59 UTC, merged